// Frontend country list — mirrors backend/src/utils/countryCodes.js.
// Keep both lists in sync: the backend is the source of truth for what gets
// stored, this copy just renders the <select> options.
export const COUNTRIES = [
  { name: 'India', dialCode: '91' },
  { name: 'United States', dialCode: '1' },
  { name: 'United Kingdom', dialCode: '44' },
  { name: 'United Arab Emirates', dialCode: '971' },
  { name: 'Australia', dialCode: '61' },
  { name: 'Canada', dialCode: '1' },
  { name: 'Nigeria', dialCode: '234' },
  { name: 'Kenya', dialCode: '254' },
  { name: 'South Africa', dialCode: '27' },
  { name: 'Singapore', dialCode: '65' },
  { name: 'Saudi Arabia', dialCode: '966' },
  { name: 'Qatar', dialCode: '974' },
  { name: 'Kuwait', dialCode: '965' },
  { name: 'Bahrain', dialCode: '973' },
  { name: 'Oman', dialCode: '968' },
  { name: 'Egypt', dialCode: '20' },
  { name: 'Pakistan', dialCode: '92' },
  { name: 'Bangladesh', dialCode: '880' },
  { name: 'Sri Lanka', dialCode: '94' },
  { name: 'Nepal', dialCode: '977' },
  { name: 'Malaysia', dialCode: '60' },
  { name: 'Indonesia', dialCode: '62' },
  { name: 'Philippines', dialCode: '63' },
  { name: 'Thailand', dialCode: '66' },
  { name: 'Vietnam', dialCode: '84' },
  { name: 'China', dialCode: '86' },
  { name: 'Hong Kong', dialCode: '852' },
  { name: 'Japan', dialCode: '81' },
  { name: 'South Korea', dialCode: '82' },
  { name: 'Israel', dialCode: '972' },
  { name: 'Turkey', dialCode: '90' },
  { name: 'Russia', dialCode: '7' },
  { name: 'Germany', dialCode: '49' },
  { name: 'France', dialCode: '33' },
  { name: 'Italy', dialCode: '39' },
  { name: 'Spain', dialCode: '34' },
  { name: 'Netherlands', dialCode: '31' },
  { name: 'Switzerland', dialCode: '41' },
  { name: 'Brazil', dialCode: '55' },
  { name: 'Mexico', dialCode: '52' },
  { name: 'Argentina', dialCode: '54' },
  { name: 'New Zealand', dialCode: '64' },
  { name: 'Ghana', dialCode: '233' },
  { name: 'Tanzania', dialCode: '255' },
  { name: 'Uganda', dialCode: '256' },
]
